### ISSUE TITLE
getevent output blocks are not newline aligned for EV_SYN events.

### ISSUE THREAD

**Issue by awalsh128** [Malinskiy/adam#103]
**Describe the bug**
When parsing events via `ChanneledShellCommandRequest("getevent -l ...")` as seen in https://github.com/awalsh128/thetowerbot/blob/e66693ce48e2c71d95fe12076ce934655766a0f4/app/src/main/kotlin/com/awalsh128/thetowerbot/AdbDevice.kt#L107 the EV_SYN event gets split into 2 parts.

So instead of getting (inserting single quotes to depict space padding)...
```
'EV_SYN       SYN_REPORT           00000000 '
```

I get ...

```
'EV_SYN       '
'SYN_REPORT           00000000 '
```

**To Reproduce**
You can run Gradle on the repo found at https://github.com/awalsh128/thetowerbot/blob/main/app/src/main/kotlin/com/awalsh128/thetowerbot/App.kt

This is being tested against a Pixel 7. I haven't been able to try it against any other devices.

**Expected behavior**
I expected to get a single line of `EV_SYN       SYN_REPORT           00000000 ` instead of the two lines as noted above.

**Logs**
* [run_l.log](https://github.com/Malinskiy/adam/files/13792616/run_l.log) - getevent with the l switch
* [run_nol.log](https://github.com/Malinskiy/adam/files/13792617/run_nol.log) - getevent without the l switch (happens for both)

**Android device (please complete the following information):**
 - Device: Pixel 7 
 - OS: Android 14
 - Adam Version 0.5.2

**Comment by Malinskiy** [comment]
Hey @awalsh128. This is because adb transport to your device splits the response into multiple packets, and [adam streams them to you ASAP](https://github.com/Malinskiy/adam/blob/master/adam/src/main/kotlin/com/malinskiy/adam/request/shell/v1/ChanneledShellCommandRequest.kt#L36). How you handle framing (i.e. presence of '\n' which I suspect is missing from the first chunk of output you have 'EV_SYN       ') of the underlying content is entirely up to you and is very specific to the command you're executing as well as how it writes to standard output + standard error

**Comment by awalsh128** [comment]
Thanks for clarifying. I'll go ahead and close this as working as intended.

BTW, what are your thoughts on using scope as a param on the function? My experience with coroutines is that they are usually extended when creating pipelines like those that incorporate channels.

**Comment by Malinskiy** [comment]
Scope is already an 'execute' function argument, which argument are you referring to?

**Comment by awalsh128** [comment]
Right, I mean in terms of your thinking doing it this way. `CoroutineScope` are usually exemplified in the Kotlin documentation as part of a pipeline where work is extended from it (i.e. `fun CoroutineScope.produceFoo(...)`). I was curious what you thought about this. Below is some similar reasoning about creating coroutines locally and then declaring as a suspendable function.

https://developer.android.com/kotlin/coroutines/coroutines-best-practices#create-coroutines-data-layer

**Comment by Malinskiy** [comment]
Here is my personal view: using CoroutineScope as a function argument is applicable when you can't model the problem space with objects. CoroutineScope is just a contract for attaching CoroutineContext to an object so effectively you're passing an execution thread pool. In this case the library is built giving maximum flexibility to the user so that you have full control over the lifecycle of background coroutines producing the events.
Ideally the coroutine scope here would be just coroutine context but produce functions require a scope, creating anonymous coroutine scope is a meh solution, that's why the argument is a scope rather than a context.

TBH I'm not really a fan of coroutine syntax since there is a lot of ambiguity with context that can happen some being implicit from the object and some explicit, so being explicit is better for clarity in my opinion. In terms of why someone would even want to specify different scope here: some of the background code for requests here runs effectively on the thread pool executor for network requests and some can run on another thread pool optionally that is used for processing results into a more user-friendly form. With explicit syntax this can be separated into different thread pools allowing you to build highly effective code that doesn't bottleneck under heavy processing. An example of this is marathon test runner where hundreds of devices on the same adb server can be processed efficiently.

**Comment by awalsh128** [comment]
Thanks for sharing your insight.
